feat: Fetch items-list for user from server
oscarine/oscarine-react-frontend pull request #66
Opened 2021-06-08 16:59 UTC by ashrafmahmood

2021-06-09 12:14 UTC, ashrafmahmood commented
@Haider8  Please check this PR

2021-06-10 06:01 UTC, Haider8 commented
@ashrafmahmood Add tests also

2021-06-14 09:09 UTC, ashrafmahmood commented
https://user-images.githubusercontent.com/55829865/121867439-973c7700-cd1d-11eb-8e2f-0c880b462377.mp4

2021-06-24 06:25 UTC, Haider8 requested changes

2021-06-24 06:25 UTC, Haider8 commented on src/components/Home/Shop.js
> +  id: PropTypes.number,
Make this a string now as I am making a slug for id using shop name

2021-06-24 06:25 UTC, Haider8 commented on src/components/Home/Shop.js
> +  id: null,
Please explain why the default is null?

2021-06-24 06:27 UTC, Haider8 commented
@ashrafmahmood Fix the deepsource issues here and then the PR will get merged

2021-06-24 08:28 UTC, ashrafmahmood commented on src/components/Home/Shop.js
> +  id: null,
Should I make it a empty string?

2021-06-24 19:12 UTC, merged